name: segregation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests
  - pip= 24.0
  - pip:
    - wandb== 0.18.5
    - scikit-learn==1.5.2
    - mlflow==2.17.0
    - pandas==2.2.2